// Generated by gencpp from file my_robot_controller/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_CONTROLLER_MESSAGE_ADDTWOINTS_H
#define MY_ROBOT_CONTROLLER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <my_robot_controller/AddTwoIntsRequest.h>
#include <my_robot_controller/AddTwoIntsResponse.h>


namespace my_robot_controller
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace my_robot_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_controller::AddTwoInts > {
  static const char* value()
  {
    return "4bac5263dd214a8605f1874d4917e35b";
  }

  static const char* value(const ::my_robot_controller::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::my_robot_controller::AddTwoInts > {
  static const char* value()
  {
    return "my_robot_controller/AddTwoInts";
  }

  static const char* value(const ::my_robot_controller::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_controller::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::my_robot_controller::AddTwoInts >
template<>
struct MD5Sum< ::my_robot_controller::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_controller::AddTwoInts >::value();
  }
  static const char* value(const ::my_robot_controller::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_controller::AddTwoIntsRequest> should match
// service_traits::DataType< ::my_robot_controller::AddTwoInts >
template<>
struct DataType< ::my_robot_controller::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_controller::AddTwoInts >::value();
  }
  static const char* value(const ::my_robot_controller::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_controller::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::my_robot_controller::AddTwoInts >
template<>
struct MD5Sum< ::my_robot_controller::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_controller::AddTwoInts >::value();
  }
  static const char* value(const ::my_robot_controller::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_controller::AddTwoIntsResponse> should match
// service_traits::DataType< ::my_robot_controller::AddTwoInts >
template<>
struct DataType< ::my_robot_controller::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_controller::AddTwoInts >::value();
  }
  static const char* value(const ::my_robot_controller::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_CONTROLLER_MESSAGE_ADDTWOINTS_H
